### ISSUE TITLE
[BUG]: Terminal pane opens whenever there is a running process in a integrated terminal

### ISSUE THREAD

**Issue by Chaitanya-Shahare** [Chaitanya-Shahare/lazygit-for-vscode#3]

**Comment by Tantol** [comment]
I have same issue

**Comment by FulecoRafa** [comment]
@Chaitanya-Shahare @Tantol Mind providing more details, like how to replicate the issue? I think I could take a look

**Comment by Tantol** [comment]
Yes ofc. sr.

In any session of using VsCode open new terminal then close panel with it and focus on editor panel. Now run "Open Lazygit". This will focus two terminals: Newly created wit Lazygit and old one from panel that was closed (hidden).

Many tasks from VsCode are running in integrated terminal that afterwards are closed (in example build of dotnet app). Now whenever I build my app, then run "Open Lazygit" I have 2 terminal focused (shown) instead of one with lazygit.

**Comment by Chaitanya-Shahare** [comment]
This issue is fixed and will be reflected in the update.
